version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build and Package (Skipping Tests)
          command: mvn -B -DskipTests package
      - persist_to_workspace:
          root: target
          paths:
            - "*.jar"
            
  deploy:
    docker:
      - image: cimg/base:2023.11
    steps:
      - attach_workspace:
          at: target
      - run:
          name: SIMULACIÓN DE DESPLIEGUE (CD COMPLETO Y EXITOSO)
          command: |
            echo "*****************************************************"
            echo "✅ SIMULACIÓN: Artefacto compilado con éxito."
            echo "Copiando archivo:"
            ls target/*.jar
            echo " "
            echo "Iniciando conexión simulada para despliegue..."
            echo "Servidor de destino (HOST): 192.168.1.100 (Inaccesible en la nube)"
            echo "Usuario (USER): neison_admin"
            echo "Ruta Remota (PATH): /var/www/staging/policlinico-app.jar"
            echo " "
            echo "✅ SIMULACIÓN: scp y ssh completados. Servicio reiniciado."
            echo "*****************************************************"
            exit 0 # FUERZA EL ÉXITO

workflows:
  version: 2
  ci_cd_full:
    jobs:
      - build
      - deploy:
          requires:
            - build # Asegura la ejecución secuencial condicional (CI -> CD)